name: build and release mod

on:
  push:
    tags:
      - "*"

env:
  BUILD_TYPE: RelWithDebInfo # So that smart IQ people can troubleshoot in case of crashes

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: build mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: "${{env.BUILD_TYPE}}"

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            [changelog.md#v${{ github.ref }}](changelog.md#v${{ github.ref }})

      - name: upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.build-output }}/zohnannor.dark_mode.geode
          asset_name: zohnannor.dark_mode.geode
          asset_content_type: application/octet-stream
