name: build and release mod

on:
  push:
    tags:
      - "*"
    branches:
      - "**"

env:
  BUILD_TYPE: RelWithDebInfo # So that smart IQ people can troubleshoot in case of crashes

jobs:
  build:
    name: build
    runs-on: windows-latest

    if: github.event_name == 'push' && (contains(github.event.head_commit.message, '[release]') || startsWith(github.ref, 'refs/tags/'))

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: build mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: "${{env.BUILD_TYPE}}"

      - name: create release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            [changelog for ${{ github.ref }}](changelog.md#${{ github.ref }})

      - name: upload release asset
        if: startsWith(github.ref, 'refs/tags/')
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.build-output }}/zohnannor.dark_mode.geode
          asset_name: zohnannor.dark_mode.geode
          asset_content_type: application/octet-stream
